// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { WorthCategory } from "./WorthCategory";

export interface ItemWorthCalculation { price: number, category: WorthCategory, count: number, detail: string | null, }