// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SkyblockGamemode } from "./SkyblockGamemode";
import type { SkyblockProfileMemberData } from "./SkyblockProfileMemberData";

export interface SkyblockProfileData { gamemode: SkyblockGamemode, bank_coins: number | null, profile_id: string, profile_name: string, members: Array<SkyblockProfileMemberData>, }