// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SPMSpecificSlayerData } from "./SPMSpecificSlayerData";

export interface SPMSlayerData { zombie: SPMSpecificSlayerData, spider: SPMSpecificSlayerData, wolf: SPMSpecificSlayerData, enderman: SPMSpecificSlayerData, blaze: SPMSpecificSlayerData, vampire: SPMSpecificSlayerData, }