// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ItemStack } from "./ItemStack";

export interface InventoryContents { inventory: Array<ItemStack>, armor: Array<ItemStack>, equipment: Array<ItemStack>, ender_chest: Array<ItemStack>, wardrobe: Array<ItemStack>, talisman_bag: Array<ItemStack>, personal_vault: Array<ItemStack>, fishing_bag: Array<ItemStack>, potion_bag: Array<ItemStack>, candy_inventory: Array<ItemStack>, storage: Array<ItemStack>, storage_icons: Array<ItemStack>, }