// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ItemWorthCalculation } from "./ItemWorthCalculation";

export interface ItemWorthResult { total: number, name: string, calculations: Array<ItemWorthCalculation>, include_calculations: boolean, }