// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { WorthResult } from "./WorthResult";

export interface NetworthResult { total: number, purse: number, bank: number, pets: Array<WorthResult>, items: Record<string, Array<WorthResult>>, sacks: Array<WorthResult>, }