// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PetWorthCalculation } from "./PetWorthCalculation";

export interface PetWorthResult { total: number, name: string, calculations: Array<PetWorthCalculation>, }