// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SkyblockChocolateFactoryTimeTower } from "./SkyblockChocolateFactoryTimeTower";
import type { SkyblockChocolateFactoryUpgrades } from "./SkyblockChocolateFactoryUpgrades";

export interface SkyblockChocolateFactoryDataSerialized { chocolate: bigint, chocolate_since_prestige: bigint, total_chocolate: bigint, chocolate_prestige: bigint, update_timestamp: number, upgrades: SkyblockChocolateFactoryUpgrades, time_tower: SkyblockChocolateFactoryTimeTower, rabbits: {[rabbit: string]: number}, }