// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface SkyblockChocolateFactoryUpgrades { click: bigint, multiplier: bigint, barn: bigint, rabbit: bigint, time_tower: bigint, rabbit_bro: bigint, rabbit_cousin: bigint, rabbit_father: bigint, rabbit_grandma: bigint, rabbit_sis: bigint, }