name: Deploy

on:
  push:
    branches:
      - master

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Sync
        uses: patrickwyler/gcs-bucket-sync-action@1.3
        with:
          secrets: ${{ secrets.google_service_account_credentials }}
          bucket: 'stats-web-files'
          exclude: '\.gitignore$|\.git/.*$|\.github/.*$|secrets\.json$'

      - name: Clear cache
        run: |
          echo "$CRED" > /secrets2.json
          gcloud auth activate-service-account --key-file=/secrets2.json
          rm /secrets2.json

          gcloud compute url-maps invalidate-cdn-cache stats-web-balancer-2 --path "/*"
        shell: bash
        env: 
          CRED: ${{ secrets.google_service_account_credentials }}