name: Deploy

on:
  push:
    branches:
      - master

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Sync
        run: |
          echo "$CRED" > /secrets.json
          gcloud auth activate-service-account --key-file=/secrets.json
          rm /secrets.json

          gsutil -m rsync -r -c -d -x "$EXCLUDE" /github/workspace/ gs://stats-web-files/

          gcloud compute url-maps invalidate-cdn-cache stats-web-balancer-2 --path "/*"
        shell: sh
        env: 
          CRED: ${{ secrets.google_service_account_credentials }}
          EXCLUDE: '\.gitignore$|\.git/.*$|\.github/.*$|secrets\.json$'